variables:
  DOCKER_SEMREL: registry.gitlab.com/juhani/go-semrel-gitlab:v0.21.1
  DOCKER_GIT: samueldebruyn/debian-git
  DOCKER_SIMPLE: alpine:3.11
  PREFIX_TAG_BUILDS: build
  PREFIX_TAG_RELEASE: release

stages:
  - Validate
  - BuildNumber
  - Build
  - Docker
  - Deploy
  - TagBuildNumber
  - TagVersion

# Templates
#######################################################################################

.lint_mr_template:
  stage: Validate
  except:
    - branches
  only:
    - merge_requests

.test_mr_template:
  stage: Validate
  except:
    - branches
  only:
    - merge_requests

.build_template:
  stage: Build
  except:
    - branches

.build_number_template:
  stage: BuildNumber
  artifacts:
    paths:
      - .build_number
      - .version

.deploy_template:
  stage: Deploy
  except:
    - branches


# Jobs
#######################################################################################

## Master jobs
#######################################################################################

CalculateBuildNumber:
  extends: .build_number_template
  image: $DOCKER_GIT
  only:
    - master
  script:
    - git rev-parse --short HEAD > .build_number
    - 'echo Calculated build number: $(cat .build_number)'

CalculateNextVersion:
  extends: .build_number_template
  image: $DOCKER_SEMREL
  variables:
    GSG_TAG_PREFIX: ''
  only:
    - master
  script:
    - release next-version --allow-current > .version

TagBuildNumber:
  stage: TagBuildNumber
  image: $DOCKER_GIT
  only:
    - master
  script:
    - export
    - BUILD_NUMBER=$(cat .build_number)
    - VERSION=$(cat .version)
    - TAG=${VERSION}.${BUILD_NUMBER}
    - 'echo Using build number: $TAG'
    - git tag $PREFIX_TAG_BUILDS/$TAG
    - git push https://gitlab-ci-token:$CI_PUSH_TOKEN@gitlab.com/$CI_PROJECT_PATH.git/ $PREFIX_TAG_BUILDS/$TAG

TagVersion:
  stage: TagVersion
  image: $DOCKER_SEMREL
  variables:
    GSG_TAG_PREFIX: $PREFIX_TAG_RELEASE
  when: manual
  only:
    - master
  script:
    - echo $GSG_TAG_PREFIX
    - release next-version
    - release tag

## Build jobs
#######################################################################################

ExtractVersionAndBuildFromBuildTAG:
  extends: .build_number_template
  image: $DOCKER_SIMPLE
  only:
    - /build/
  script:
    - echo $CI_COMMIT_TAG | sed -n -E 's/build\/([0-9]+.[0-9]+.[0-9]+).([[:alnum:]]{7})/\2/p' > .build_number
    - echo $CI_COMMIT_TAG | sed -n -E 's/build\/([0-9]+.[0-9]+.[0-9]+).*/\1/p' > .version
    - 'echo Version: $(cat .version) - Build: $(cat .build_number)'

## Release jobs
#######################################################################################

BuildNumberFromReleaseTAG:
  extends: .build_number_template
  image: $DOCKER_SIMPLE
  only:
    - /release/
  script:
    - echo $CI_COMMIT_TAG | sed -n -E 's/release\/([0-9]+.[0-9]+.[0-9]+)/\1/p' > .version
    - 'echo Version $(cat .version)'
