variables:
  DOCKER_SEMREL: registry.gitlab.com/juhani/go-semrel-gitlab:v0.21.1
  DOCKER_TFENV: marmarama/tfenv
  GSG_BUMP_PATCH: 1
  GSG_TAG_PREFIX: ''
  TF_IN_AUTOMATION: 1
  TF_INPUT: 0
  TF_CLI_ARGS_init: '-backend-config="token=$TERRAFORM_BACKEND_TOKEN" -input=false'
  TF_CLI_ARGS_plan: '-input=false -out tfPlan'
  TF_CLI_ARGS_apply: '-input=false'

stages:
  - Validation
  - TagVersion
  - Deploy

# Templates
#######################################################################################

## Script templates
#######################################################################################

.job_template: &terraform_install tfenv install

.job_template: &terraform_init terraform init

.job_template: &terraform_plan terraform plan

.job_template: &terraform_apply terraform apply tfPlan

## Job templates
#######################################################################################

.validate_template:
  stage: Validation
  image: $DOCKER_TFENV
  variables:
    SHOULD_PLAN: 1
  script:
    - *terraform_install
    - *terraform_init
    - terraform validate
    - if [ $SHOULD_PLAN -eq 1 ]; then *terraform_plan; fi
  
.deploy_template:
  stage: Deploy
  image: $DOCKER_TFENV
  only:
    - tags
  script:
    - *terraform_install
    - *terraform_init
    - *terraform_plan
    - *terraform

# Jobs
#######################################################################################

Version:
  stage: TagVersion
  image: registry.gitlab.com/juhani/go-semrel-gitlab:v0.21.1
  only:
    - master
  script:
    - release next-version
    - release tag
