#!/bin/bash

# List the branch prefixes that apply, bellow
if [ -z "$BRANCHES_TO_APPLY" ]; then
	BRANCHES_TO_APPLY=(chore fix feat)
fi

# Pick the current branch name
BRANCH_NAME=$(git symbolic-ref --short HEAD)

# Remove the unnecessary parts
TRIMMED=$(echo $BRANCH_NAME | cut -d/ -f1 | tr "[:upper:]" "[:lower:]")

# If it matches, prepend the part that interests us to the given commit message
if [[ ${BRANCHES_TO_APPLY[*]} == *"$TRIMMED"* ]]; then
	sed -i.bak -e "/^$TRIMMED/! s/^/$TRIMMED: /" $1
fi
