include:
  - remote: https://github.com/YData-ai/Playbook/raw/master/pipelines/templates/base-gitlab-ci.yml

# Templates
#######################################################################################

.docker_template:
  stage: Docker
  image: docker:stable
  except:
    - branches
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - docker:19.03.0-dind
  script:
    - BUILD_NUMBER=$(cat .build_number)
    - 'echo Building docker image for: $BUILD_NUMBER'
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH/$REGISTRY_PATH:$BUILD_NUMBER .
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH/$REGISTRY_PATH:$BUILD_NUMBER

## Build jobs
#######################################################################################

BuildDockerForBuildTag:
  extends: .docker_template
  variables:
    REGISTRY_PATH: $PREFIX_TAG_BUILDS
  only:
    - /build/

BuildDockerForReleaseTag:
  extends: .docker_template
  variables:
    REGISTRY_PATH: $PREFIX_TAG_RELEASE
  only:
    - /release/
